import Head from 'next/head'
import Header from '../components/Header'
import LatestPost from '../components/LatestPostSection'
import Navbar from '../components/Navbar'
import Trending from '../components/TrendingSection'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Medium Where good ideas find you.</title>
        <meta
          name='description'
          content='Generated by create NextApp'>
        </meta>
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <Header />
      <Trending />
      <LatestPost />
    </>
  )
}
